name: Injector

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build-linux-x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: "Download Godot"
        run: wget https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip && unzip Godot_v4.3-stable_linux.x86_64.zip

      - name: "Create PCK"
        run: ./Godot_v4.3-stable_linux.x86_64 --headless --path Injector --export-pack PCK "$PWD/Injector.pck"

      - uses: actions/upload-artifact@v4
        with:
          name: Injector.pck
          path: Injector.pck